### ISSUE TITLE
Any ideas to add blinks ?

### ISSUE THREAD

**Issue by alter-sachin** [Rudrabha/LipGAN#38]
Hello
This works really well, I was wondering if we could add blinks to the eyes in some way, this would create more realism in the videos generated from the single image.
Any pointers would be lovely

**Comment by prajwalkr** [comment]
Hello, you can take a look at https://github.com/AliaksandrSiarohin/first-order-model to animate a single image and then take an inference on that. 

We also suggest you take an inference on a short video (or the animated video from above) instead of a static image, using our new improved model: https://github.com/Rudrabha/Wav2Lip
